### ISSUE TITLE
Publish OSCAL-CAT (Catalog Authoring Tool) on pages.nist.gov (HackMD.IO Tools: Issue #2)

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/oscal-cat#11]
# Description

As a developer of the tool, in order to ensure it was properly designed, implemented, and tested, I want a checklist of requirements and evidence of their completion to understand the quality measures completed as required for deployment the pages.nist.gov service.

# Goals

The following NIST requirements must be met:
- [x] [NIST S 1801.03](https://inet.nist.gov/system/files/documents/2021/12/29/final-s-1801_03-ver-3.pdf) (supplemented by [this checklist](https://inet.nist.gov/system/files/documents/2022/04/27/checklist-for-software-form-2022-04-27%20.pdf))
    - [x] **How do you expect your code/software to be used** *(choose 1)*:
        - ~Code is informational (e.g. part of the supplemental information in a narrative publication) and not intended for re-use~
        - **Code itself is intended for re-use (e.g. in a specific scientific area) or the public is being invited to contribute to it**
    - [x] **Developing and Testing:**
        - [x] A testing plan was developed, followed, and documented. The testing plan is available at a specified link. usnistgov/oscal-cat#20
        - [x] Continuous testing was conducted during updates and new builds in usnistgov/oscal-cat#20
        - [x] Code includes appropriate IT security and privacy controls in usnistgov/oscal-cat#20
    - [x] **Documenting:**
        - [x] Documentation is available as appropriate as: *(choose 1)*
            - [x] Integrated with the source code
            - [x] On separate web pages (e.g. nist.gov, pages.nist.gov) https://github.com/usnistgov/oscal-tools/pull/60
            - ~In a separate publication~
            - ~Other~
        - [x] Documentation includes, as appropriate:
            - [x] README
            - ~[ ] Function-level documentation~
            - [x] #32
            - [x] Installation instructions
            - ~User instructions/guides in usnistgov/oscal-cat#5~
            - [x] ~API Specification~
            - ~A changelog file (included in GitHub releases) https://github.com/usnistgov/oscal-cat/issues/29~
            - [x] Specification of maturity level (i.e. is the software still being developed,, are you expecting feedback on performance and usability, is the project completed) https://github.com/usnistgov/oscal-tools/pull/60 and https://github.com/usnistgov/oscal-cat/issues/36
            - [x] A communication to users of your intent to provide (or not provide) support https://github.com/usnistgov/oscal-tools/pull/60 and https://github.com/usnistgov/oscal-cat/issues/36
            - ~Information about how a binary was produced~
    - [x] **License and disclaimers:**
        - [x] #22
        - [x] ~External collaborators who were part of this project have been credited~
        - [x] Third-party software licenses permit modification and/or redistribution
            - [x] Appropriate licensing is included
            - [x] Files modified by NIST contain notice that modifications are released to the public domain as appropriate #22
- [x] [Fair Principles](https://github.com/usnistgov/opensource-repo/blob/3039806ce93fe5afd6a9535edf305188ee196346/fair-software.md) (supplemented by [this checklist](https://github.com/usnistgov/opensource-repo/blob/3039806ce93fe5afd6a9535edf305188ee196346/fair-software.md#make-it-fair-in-ten-easy-steps))
    - [x] Findable (Will be satisfied by MIDAS entry) https://github.com/usnistgov/oscal-cat/issues/35
        - [x] (Meta)data are assigned a globally unique and persistent identifier https://github.com/usnistgov/oscal-cat/issues/33
        - [x] Data are described with rich metadata (defined by R1 below) https://github.com/usnistgov/oscal-cat/issues/33
        - [x] Metadata clearly and explicitly include the identifier of the data they describe
        - [x] (Meta)data are registered or indexed in a searchable resource https://github.com/usnistgov/oscal-cat/issues/33
    - [x] Accessible (satisfied by Github)
        - [x] (Meta)data are retrievable by their identifier using a standardized communications protocol https://github.com/usnistgov/oscal-cat/issues/33
        - [x] Metadata are accessible, even when the data are no longer available https://github.com/usnistgov/oscal-cat/issues/35
    - [x] Interoperable (satisfied by GitHub)
        - [x] (Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation. https://github.com/usnistgov/oscal-cat/issues/33
        - [x] (Meta)data use vocabularies that follow FAIR principles https://github.com/usnistgov/oscal-cat/issues/33
        - [x] (Meta)data include qualified references to other (meta)data https://github.com/usnistgov/oscal-cat/issues/33 and code.nist.gov indexing
    - [x] Reusable (satisfied by GitHub)
        - [x] (Meta)data are richly described with a plurality of accurate and relevant attributes 
            - [x] (Meta)data are released with a clear and accessible data usage license
            - [x] (Meta)data are associated with detailed provenance 
            - [x] (Meta)data meet domain-relevant community standards https://github.com/usnistgov/oscal-cat/issues/33
Follow-on requirements:
- [x] Set up branch protections and require code reviews for `main` https://github.com/usnistgov/oscal-cat/issues/54
- [x] Set up and document development on `develop` and feature branches https://github.com/usnistgov/oscal-cat/issues/54
- [x] Set up process for tagging branch/commit for releases and bundling a tagged release https://github.com/usnistgov/oscal-cat/issues/54
- ~#5~
- ~#29~
- [x] #60

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist #60 is done. #5 is not expressly included in this sprint, but #11 and related work is a blocker. We talk on Tuesday about how we and @JustKuzya want these things done before the mini-workshop some time next week?

**Comment by aj-stein-nist** [comment]
Per Dave's request in today's sync, we are going to to resolve this as more or less complete and create targeted issues for release and post-release checklist to prioritize items in respective issues for both. So ... closing out!
