### ISSUE TITLE
Publish OSCAL-CAT (Catalog Authoring Tool ) as an open-source repo (HackMD.IO Tools: Issue #1)

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/oscal-cat#9]
The following actions will be required for the task:

- [x] Address all vulnerabilities from the "audit-tool" trail and "dependabot" recommendations (to be worked on in the following issues: #4)
- [x] #39
- [x]  Add NIST standard comment-header to the relevant files and the repository #22 
- [ ] Complete NIST-required check-list for publishing the source code #11
